version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
#      RABBITMQ_DEFAULT_USER: "rabbitmq"
#      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "15675:15675"
      - "5672:5672"
      - "1883:1883"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

  sensor-ui:
    build: .
    ports:
      - "8080:80"

  owm-sensor:
    build: python/.

